from item import item 
from item import consumable
import random

bananas = consumable("Bananas", "Bananas", ["hp", random.randint(1, 8)], isFood = True)
breadcrumbs = consumable("Breadcrumbs", "Breadcrumbs", ["hp", random.randint(1,8)], isFood = True)
almond_paste = consumable("Almond Paste", "Almond Paste", ["hp", random.randint(1,8)], isFood=True)
anchovies = consumable("Anchovies", "Anchovies", ["hp", random.randint(1,8)], isFood=True)
garlic = consumable("Garlic", "Garlic", ["hp", random.randint(1,8)], isFood = True)
lamb = consumable("Lamb", "Lamb", ["hp",random.randint(1,8)], isFood = True)
walnuts = consumable("Walnuts", "Walnuts", ["hp",random.randint(1,8)], isFood = True)
raisins = consumable("Raisins", "Raisins", ["hp",random.randint(1,8)], isFood = True)
artichokes = consumable("Artichokes", "Artichokes", ["hp",random.randint(1,8)], isFood = True)
pears = consumable("Pears", "Pears", ["hp",random.randint(1,8)], isFood = True)
parsnips = consumable("Parsnips", "Parsnips", ["hp",random.randint(1,8)], isFood = True)
dumpling = consumable("Dumpling", "Dumpling", ["hp",random.randint(1,8)], isFood = True)
olive_oil = consumable("Olive oil", "Olive oil", ["hp",random.randint(1,8)], isFood = True)
swiss_cheese = consumable("Swiss cheese", "Swiss cheese", ["hp",random.randint(1,8)], isFood = True)
bean_sprouts = consumable("Bean sprouts", "Bean sprouts", ["hp",random.randint(1,8)], isFood = True)
beer = consumable("Beer", "Beer", ["hp",random.randint(1,8)], isFood = True)
breadcrumbs = consumable("Breadcrumbs", "Breadcrumbs", ["hp",random.randint(1,8)], isFood = True)
fennel_seeds = consumable("Fennel seeds", "Fennel seeds", ["hp",random.randint(1,8)], isFood = True)
truffles = consumable("Truffles", "Truffles", ["hp",random.randint(1,8)], isFood = True)
oranges = consumable("Oranges", "Oranges", ["hp",random.randint(1,8)], isFood = True)
almonds = consumable("Almonds", "Almonds", ["hp",random.randint(1,8)], isFood = True)
dried_leeks = consumable("Dried leeks", "Dried leeks", ["hp",random.randint(1,8)], isFood = True)
vanilla_bean = consumable("Vanilla bean", "Vanilla bean", ["hp",random.randint(1,8)], isFood = True)
oatmeal = consumable("Oatmeal", "Oatmeal", ["hp",random.randint(1,8)], isFood = True)
apricots = consumable("Apricots", "Apricots", ["hp",random.randint(1,8)], isFood = True)
dill = consumable("Dill", "Dill", ["hp",random.randint(1,8)], isFood = True)
rum = consumable("Rum", "Rum", ["hp",random.randint(1,8)], isFood = True)
crayfish = consumable("Crayfish", "Crayfish", ["hp",random.randint(1,8)], isFood = True)
white_beans = consumable("White beans", "White beans", ["hp",random.randint(1,8)], isFood = True)
tomato_sauce = consumable("Tomato sauce", "Tomato sauce", ["hp",random.randint(1,8)], isFood = True)
feta_cheese = consumable("Feta cheese", "Feta cheese", ["hp",random.randint(1,8)], isFood = True)
zinfandel_wine = consumable("Zinfandel wine", "Zinfandel wine", ["hp",random.randint(1,8)], isFood = True)
duck = consumable("Duck", "Duck", ["hp",random.randint(1,8)], isFood = True)
chicken_liver = consumable("Chicken liver", "Chicken liver", ["hp",random.randint(1,8)], isFood = True)
broccoli_raab = consumable("Broccoli raab", "Broccoli raab", ["hp",random.randint(1,8)], isFood = True)
steak = consumable("Steak", "Steak", ["hp",random.randint(1,8)], isFood = True)
pancetta = consumable("Pancetta", "Pancetta", ["hp",random.randint(1,8)], isFood = True)
arugula = consumable("Arugula", "Arugula", ["hp",random.randint(1,8)], isFood = True)
kale = consumable("Kale", "Kale", ["hp",random.randint(1,8)], isFood = True)
oatmeal = consumable("Oatmeal", "Oatmeal", ["hp",random.randint(1,8)], isFood = True)
green_beans = consumable("Green beans", "Green beans", ["hp",random.randint(1,8)], isFood = True)
pea_beans = consumable("Pea beans", "Pea beans", ["hp",random.randint(1,8)], isFood = True)
rice_wine = consumable("Rice wine", "Rice wine", ["hp",random.randint(1,8)], isFood = True)
cider = consumable("Cider", "Cider", ["hp",random.randint(1,8)], isFood = True)
anchovy_paste = consumable("Anchovy paste", "Anchovy paste", ["hp",random.randint(1,8)], isFood = True)
prawns = consumable("Prawns", "Prawns", ["hp",random.randint(1,8)], isFood = True)
water_chestnuts = consumable("Water chestnuts", "Water chestnuts", ["hp",random.randint(1,8)], isFood = True)
ham = consumable("Ham", "Ham", ["hp",random.randint(1,8)], isFood = True)
lamb = consumable("Lamb", "Lamb", ["hp",random.randint(1,8)], isFood = True)
gouda = consumable("Gouda", "Gouda", ["hp",random.randint(1,8)], isFood = True)
octopus = consumable("Octopus", "Octopus", ["hp",random.randint(1,8)], isFood = True)
provolone = consumable("Provolone", "Provolone", ["hp",random.randint(1,8)], isFood = True)
sage = consumable("Sage", "Sage", ["hp",random.randint(1,8)], isFood = True)
peas = consumable("Peas", "Peas", ["hp",random.randint(1,8)], isFood = True)
adobo = consumable("Adobo", "Adobo", ["hp",random.randint(1,8)], isFood = True)
blueberries = consumable("Blueberries", "Blueberries", ["hp",random.randint(1,8)], isFood = True)
raw_sugar = consumable("Raw sugar", "Raw sugar", ["hp",random.randint(1,8)], isFood = True)
herring = consumable("Herring", "Herring", ["hp",random.randint(1,8)], isFood = True)
shitakes = consumable("Shitakes", "Shitakes", ["hp",random.randint(1,8)], isFood = True)
bay_leaves = consumable("Bay leaves", "Bay leaves", ["hp",random.randint(1,8)], isFood = True)
chai = consumable("Chai", "Chai", ["hp",random.randint(1,8)], isFood = True)
cucumbers = consumable("Cucumbers", "Cucumbers", ["hp",random.randint(1,8)], isFood = True)
sugar = consumable("Sugar", "Sugar", ["hp",random.randint(1,8)], isFood = True)
snow_peas = consumable("Snow peas", "Snow peas", ["hp",random.randint(1,8)], isFood = True)
apples = consumable("Apples", "Apples", ["hp",random.randint(1,8)], isFood = True)
sausages = consumable("Sausages", "Sausages", ["hp",random.randint(1,8)], isFood = True)
chili_sauce = consumable("Chili sauce", "Chili sauce", ["hp",random.randint(1,8)], isFood = True)
Tabasco_sauce = consumable("Tabasco sauce", "Tabasco sauce", ["hp",random.randint(1,8)], isFood = True)
beef = consumable("Beef", "Beef", ["hp",random.randint(1,8)], isFood = True)
poppy_seeds = consumable("Poppy seeds", "Poppy seeds", ["hp",random.randint(1,8)], isFood = True)
coffee = consumable("Coffee", "Coffee", ["hp",random.randint(1,8)], isFood = True)
mayonnaise = consumable("Mayonnaise", "Mayonnaise", ["hp",random.randint(1,8)], isFood = True)
broth = consumable("Broth", "Broth", ["hp",random.randint(1,8)], isFood = True)
cayenne_pepper = consumable("Cayenne pepper", "Cayenne pepper", ["hp",random.randint(1,8)], isFood = True)
raisins = consumable("Raisins", "Raisins", ["hp",random.randint(1,8)], isFood = True)
salmon = consumable("Salmon", "Salmon", ["hp",random.randint(1,8)], isFood = True)
barley_sugar = consumable("Barley sugar", "Barley sugar", ["hp",random.randint(1,8)], isFood = True)
prunes = consumable("Prunes", "Prunes", ["hp",random.randint(1,8)], isFood = True)
clams = consumable("Clams", "Clams", ["hp",random.randint(1,8)], isFood = True)
asparagus = consumable("Asparagus", "Asparagus", ["hp",random.randint(1,8)], isFood = True)
pears = consumable("Pears", "Pears", ["hp",random.randint(1,8)], isFood = True)
wild_rice = consumable("Wild rice", "Wild rice", ["hp",random.randint(1,8)], isFood = True)
cumin = consumable("Cumin", "Cumin", ["hp",random.randint(1,8)], isFood = True)
tomato_paste = consumable("Tomato paste", "Tomato paste", ["hp",random.randint(1,8)], isFood = True)
cooking_wine = consumable("Cooking wine", "Cooking wine", ["hp",random.randint(1,8)], isFood = True)
brussels_sprouts = consumable("Brussels sprouts", "Brussels sprouts", ["hp",random.randint(1,8)], isFood = True)
halibut = consumable("Halibut", "Halibut", ["hp",random.randint(1,8)], isFood = True)
chives = consumable("Chives", "Chives", ["hp",random.randint(1,8)], isFood = True)
oranges = consumable("Oranges", "Oranges", ["hp",random.randint(1,8)], isFood = True)
hash_browns = consumable("Hash browns", "Hash browns", ["hp",random.randint(1,8)], isFood = True)
lemon_grass = consumable("Lemon grass", "Lemon grass", ["hp",random.randint(1,8)], isFood = True)
croutons = consumable("Croutons", "Croutons", ["hp",random.randint(1,8)], isFood = True)
focaccia = consumable("Focaccia", "Focaccia", ["hp",random.randint(1,8)], isFood = True)
geese = consumable("Geese", "Geese", ["hp",random.randint(1,8)], isFood = True)
cranberries = consumable("Cranberries", "Cranberries", ["hp",random.randint(1,8)], isFood = True)
cornstarch = consumable("Cornstarch", "Cornstarch", ["hp",random.randint(1,8)], isFood = True)
jelly_beans = consumable("Jelly beans", "Jelly beans", ["hp",random.randint(1,8)], isFood = True)
sesame_seeds = consumable("Sesame seeds", "Sesame seeds", ["hp",random.randint(1,8)], isFood = True)
bouillon = consumable("Bouillon", "Bouillon", ["hp",random.randint(1,8)], isFood = True)
chicory = consumable("Chicory", "Chicory", ["hp",random.randint(1,8)], isFood = True)
couscous = consumable("Couscous", "Couscous", ["hp",random.randint(1,8)], isFood = True)
condensed_milk = consumable("Condensed milk", "Condensed milk", ["hp",random.randint(1,8)], isFood = True)
honeydew_melons = consumable("Honeydew melons", "Honeydew melons", ["hp",random.randint(1,8)], isFood = True)
ketchup = consumable("Ketchup", "Ketchup", ["hp",random.randint(1,8)], isFood = True)
mint = consumable("Mint", "Mint", ["hp",random.randint(1,8)], isFood = True)
bean_threads = consumable("Bean threads", "Bean threads", ["hp",random.randint(1,8)], isFood = True)
curry_powder = consumable("Curry powder", "Curry powder", ["hp",random.randint(1,8)], isFood = True)
okra = consumable("Okra", "Okra", ["hp",random.randint(1,8)], isFood = True)
carrots = consumable("Carrots", "Carrots", ["hp",random.randint(1,8)], isFood = True)
sweet_peppers = consumable("Sweet peppers", "Sweet peppers", ["hp",random.randint(1,8)], isFood = True)
brandy = consumable("Brandy", "Brandy", ["hp",random.randint(1,8)], isFood = True)
eggplants = consumable("Eggplants", "Eggplants", ["hp",random.randint(1,8)], isFood = True)
parsnips = consumable("Parsnips", "Parsnips", ["hp",random.randint(1,8)], isFood = True)
apricots = consumable("Apricots", "Apricots", ["hp",random.randint(1,8)], isFood = True)
sardines = consumable("Sardines", "Sardines", ["hp",random.randint(1,8)], isFood = True)
Canadian_bacon = consumable("Canadian bacon", "Canadian bacon", ["hp",random.randint(1,8)], isFood = True)
swiss_cheese = consumable("Swiss cheese", "Swiss cheese", ["hp",random.randint(1,8)], isFood = True)
vinegar = consumable("Vinegar", "Vinegar", ["hp",random.randint(1,8)], isFood = True)
almonds = consumable("Almonds", "Almonds", ["hp",random.randint(1,8)], isFood = True)
bean_sauce = consumable("Bean sauce", "Bean sauce", ["hp",random.randint(1,8)], isFood = True)
salt = consumable("Salt", "Salt", ["hp",random.randint(1,8)], isFood = True)
blue_cheese = consumable("Blue cheese", "Blue cheese", ["hp",random.randint(1,8)], isFood = True)
kumquats = consumable("Kumquats", "Kumquats", ["hp",random.randint(1,8)], isFood = True)
orange_peels = consumable("Orange peels", "Orange peels", ["hp",random.randint(1,8)], isFood = True)
crayfish = consumable("Crayfish", "Crayfish", ["hp",random.randint(1,8)], isFood = True)
tea = consumable("Tea", "Tea", ["hp",random.randint(1,8)], isFood = True)
pickles = consumable("Pickles", "Pickles", ["hp",random.randint(1,8)], isFood = True)
snap_peas = consumable("Snap peas", "Snap peas", ["hp",random.randint(1,8)], isFood = True)
colby_cheese = consumable("Colby cheese", "Colby cheese", ["hp",random.randint(1,8)], isFood = True)
artificial_sweetener = consumable("Artificial sweetener", "Artificial sweetener", ["hp",random.randint(1,8)], isFood = True)
red_pepper_flakes = consumable("Red pepper flakes", "Red pepper flakes", ["hp",random.randint(1,8)], isFood = True)
aioli = consumable("Aioli", "Aioli", ["hp",random.randint(1,8)], isFood = True)
zinfandel_wine = consumable("Zinfandel wine", "Zinfandel wine", ["hp",random.randint(1,8)], isFood = True)
hazelnuts = consumable("Hazelnuts", "Hazelnuts", ["hp",random.randint(1,8)], isFood = True)
gorgonzola = consumable("Gorgonzola", "Gorgonzola", ["hp",random.randint(1,8)], isFood = True)
maple_syrup = consumable("Maple syrup", "Maple syrup", ["hp",random.randint(1,8)], isFood = True)
cannellini_beans = consumable("Cannellini beans", "Cannellini beans", ["hp",random.randint(1,8)], isFood = True)
alligator = consumable("Alligator", "Alligator", ["hp",random.randint(1,8)], isFood = True)
habanero_chilies = consumable("Habanero chilies", "Habanero chilies", ["hp",random.randint(1,8)], isFood = True)
sea_cucumbers = consumable("Sea cucumbers", "Sea cucumbers", ["hp",random.randint(1,8)], isFood = True)
spinach = consumable("Spinach", "Spinach", ["hp",random.randint(1,8)], isFood = True)
brown_sugar = consumable("Brown sugar", "Brown sugar", ["hp",random.randint(1,8)], isFood = True)
olive_oil = consumable("Olive oil", "Olive oil", ["hp",random.randint(1,8)], isFood = True)
vermouth = consumable("Vermouth", "Vermouth", ["hp",random.randint(1,8)], isFood = True)
coconut_milk = consumable("Coconut milk", "Coconut milk", ["hp",random.randint(1,8)], isFood = True)
veal = consumable("Veal", "Veal", ["hp",random.randint(1,8)], isFood = True)
peaches = consumable("Peaches", "Peaches", ["hp",random.randint(1,8)], isFood = True)
Irish_cream_liqueur = consumable("Irish cream liqueur", "Irish cream liqueur", ["hp",random.randint(1,8)], isFood = True)
marmalade = consumable("Marmalade", "Marmalade", ["hp",random.randint(1,8)], isFood = True)
borscht = consumable("Borscht", "Borscht", ["hp",random.randint(1,8)], isFood = True)
coriander = consumable("Coriander", "Coriander", ["hp",random.randint(1,8)], isFood = True)
milk = consumable("Milk", "Milk", ["hp",random.randint(1,8)], isFood = True)
cabbage = consumable("Cabbage", "Cabbage", ["hp",random.randint(1,8)], isFood = True)
mozzarella = consumable("Mozzarella", "Mozzarella", ["hp",random.randint(1,8)], isFood = True)
dumpling = consumable("Dumpling", "Dumpling", ["hp",random.randint(1,8)], isFood = True)
angelica = consumable("Angelica", "Angelica", ["hp",random.randint(1,8)], isFood = True)
Cappuccino_Latte = consumable("Cappuccino latte", "Cappuccino latte", ["hp",random.randint(1,8)], isFood = True)
ginger_ale = consumable("Ginger ale", "Ginger ale", ["hp",random.randint(1,8)], isFood = True)
molasses = consumable("Molasses", "Molasses", ["hp",random.randint(1,8)], isFood = True)
turkeys = consumable("Turkeys", "Turkeys", ["hp",random.randint(1,8)], isFood = True)
cauliflower = consumable("Cauliflower", "Cauliflower", ["hp",random.randint(1,8)], isFood = True)
ricotta_cheese = consumable("Ricotta cheese", "Ricotta cheese", ["hp",random.randint(1,8)], isFood = True)
white_chocolate = consumable("White chocolate", "White chocolate", ["hp",random.randint(1,8)], isFood = True)
rabbits = consumable("Rabbits", "Rabbits", ["hp",random.randint(1,8)], isFood = True)
quail = consumable("Quail", "Quail", ["hp",random.randint(1,8)], isFood = True)
apple_pie_spice = consumable("Apple pie spice", "Apple pie spice", ["hp",random.randint(1,8)], isFood = True)
celery = consumable("Celery", "Celery", ["hp",random.randint(1,8)], isFood = True)
pasta = consumable("Pasta", "Pasta", ["hp",random.randint(1,8)], isFood = True)
Marsala = consumable("Marsala", "Marsala", ["hp",random.randint(1,8)], isFood = True)
cactus = consumable("Cactus", "Cactus", ["hp",random.randint(1,8)], isFood = True)
onion_powder = consumable("Onion powder", "Onion powder", ["hp",random.randint(1,8)], isFood = True)
mustard_seeds = consumable("Mustard seeds", "Mustard seeds", ["hp",random.randint(1,8)], isFood = True)
panko_bread_crumbs = consumable("Panko bread crumbs", "Panko bread crumbs", ["hp",random.randint(1,8)], isFood = True)
canola_oil = consumable("Canola oil", "Canola oil", ["hp",random.randint(1,8)], isFood = True)
chili_powder = consumable("Chili powder", "Chili powder", ["hp",random.randint(1,8)], isFood = True)
papayas = consumable("Papayas", "Papayas", ["hp",random.randint(1,8)], isFood = True)
scallops = consumable("Scallops", "Scallops", ["hp",random.randint(1,8)], isFood = True)
lentils = consumable("Lentils", "Lentils", ["hp",random.randint(1,8)], isFood = True)
lemon_juice = consumable("Lemon juice", "Lemon juice", ["hp",random.randint(1,8)], isFood = True)
pineapples = consumable("Pineapples", "Pineapples", ["hp",random.randint(1,8)], isFood = True)
cornmeal = consumable("Cornmeal", "Cornmeal", ["hp",random.randint(1,8)], isFood = True)
pistachios = consumable("Pistachios", "Pistachios", ["hp",random.randint(1,8)], isFood = True)
allspice = consumable("Allspice", "Allspice", ["hp",random.randint(1,8)], isFood = True)
radishes = consumable("Radishes", "Radishes", ["hp",random.randint(1,8)], isFood = True)
vegemite = consumable("Vegemite", "Vegemite", ["hp",random.randint(1,8)], isFood = True)
chestnuts = consumable("Chestnuts", "Chestnuts", ["hp",random.randint(1,8)], isFood = True)
five_spice_powder = consumable("Five-spice powder", "Five-spice powder", ["hp",random.randint(1,8)], isFood = True)
flounder = consumable("Flounder", "Flounder", ["hp",random.randint(1,8)], isFood = True)
Kahlua = consumable("Kahlua", "Kahlua", ["hp",random.randint(1,8)], isFood = True)
granola = consumable("Granola", "Granola", ["hp",random.randint(1,8)], isFood = True)
sour_cream = consumable("Sour cream", "Sour cream", ["hp",random.randint(1,8)], isFood = True)
blackberries = consumable("Blackberries", "Blackberries", ["hp",random.randint(1,8)], isFood = True)
black_beans = consumable("Black beans", "Black beans", ["hp",random.randint(1,8)], isFood = True)
moo_shu_wrappers = consumable("Moo shu wrappers", "Moo shu wrappers", ["hp",random.randint(1,8)], isFood = True)
pesto = consumable("Pesto", "Pesto", ["hp",random.randint(1,8)], isFood = True)
white_beans = consumable("White beans", "White beans", ["hp",random.randint(1,8)], isFood = True)
lemons = consumable("Lemons", "Lemons", ["hp",random.randint(1,8)], isFood = True)
rosemary = consumable("Rosemary", "Rosemary", ["hp",random.randint(1,8)], isFood = True)
cheddar_cheese = consumable("Cheddar cheese", "Cheddar cheese", ["hp",random.randint(1,8)], isFood = True)
soymilk = consumable("Soymilk", "Soymilk", ["hp",random.randint(1,8)], isFood = True)
chambord = consumable("Chambord", "Chambord", ["hp",random.randint(1,8)], isFood = True)
wine_vinegar = consumable("Wine vinegar", "Wine vinegar", ["hp",random.randint(1,8)], isFood = True)
mackerel = consumable("Mackerel", "Mackerel", ["hp",random.randint(1,8)], isFood = True)
andouille_sausage = consumable("Andouille sausage", "Andouille sausage", ["hp",random.randint(1,8)], isFood = True)
margarine = consumable("Margarine", "Margarine", ["hp",random.randint(1,8)], isFood = True)
haddock = consumable("Haddock", "Haddock", ["hp",random.randint(1,8)], isFood = True)
remoulade = consumable("Remoulade", "Remoulade", ["hp",random.randint(1,8)], isFood = True)
kiwi = consumable("Kiwi", "Kiwi", ["hp",random.randint(1,8)], isFood = True)
zest = consumable("Zest", "Zest", ["hp",random.randint(1,8)], isFood = True)
potato_chips = consumable("Potato chips", "Potato chips", ["hp",random.randint(1,8)], isFood = True)
garlic_powder = consumable("Garlic powder", "Garlic powder", ["hp",random.randint(1,8)], isFood = True)
flour = consumable("Flour", "Flour", ["hp",random.randint(1,8)], isFood = True)
steak = consumable("Steak", "Steak", ["hp",random.randint(1,8)], isFood = True)
grapes = consumable("Grapes", "Grapes", ["hp",random.randint(1,8)], isFood = True)
swordfish = consumable("Swordfish", "Swordfish", ["hp",random.randint(1,8)], isFood = True)
creme_fraiche = consumable("Creme fraiche", "Creme fraiche", ["hp",random.randint(1,8)], isFood = True)
fennel_seeds = consumable("Fennel seeds", "Fennel seeds", ["hp",random.randint(1,8)], isFood = True)
olives = consumable("Olives", "Olives", ["hp",random.randint(1,8)], isFood = True)
curry_paste = consumable("Curry paste", "Curry paste", ["hp",random.randint(1,8)], isFood = True)
brunoise = consumable("Brunoise", "Brunoise", ["hp",random.randint(1,8)], isFood = True)
strawberries = consumable("Strawberries", "Strawberries", ["hp",random.randint(1,8)], isFood = True)
chutney = consumable("Chutney", "Chutney", ["hp",random.randint(1,8)], isFood = True)
Goji_berry = consumable("Goji berry", "Goji berry", ["hp",random.randint(1,8)], isFood = True)
broccoli = consumable("Broccoli", "Broccoli", ["hp",random.randint(1,8)], isFood = True)
cloves = consumable("Cloves", "Cloves", ["hp",random.randint(1,8)], isFood = True)
hoisin_sauce = consumable("Hoisin sauce", "Hoisin sauce", ["hp",random.randint(1,8)], isFood = True)
guavas = consumable("Guavas", "Guavas", ["hp",random.randint(1,8)], isFood = True)
rhubarb = consumable("Rhubarb", "Rhubarb", ["hp",random.randint(1,8)], isFood = True)
artichokes = consumable("Artichokes", "Artichokes", ["hp",random.randint(1,8)], isFood = True)
fish_sauce = consumable("Fish sauce", "Fish sauce", ["hp",random.randint(1,8)], isFood = True)
custard = consumable("Custard", "Custard", ["hp",random.randint(1,8)], isFood = True)
won_ton_skins = consumable("Won ton skins", "Won ton skins", ["hp",random.randint(1,8)], isFood = True)
pomegranates = consumable("Pomegranates", "Pomegranates", ["hp",random.randint(1,8)], isFood = True)
sherry = consumable("Sherry", "Sherry", ["hp",random.randint(1,8)], isFood = True)
eggs = consumable("Eggs", "Eggs", ["hp",random.randint(1,8)], isFood = True)
jicama = consumable("Jicama", "Jicama", ["hp",random.randint(1,8)], isFood = True)
parsley = consumable("Parsley", "Parsley", ["hp",random.randint(1,8)], isFood = True)
Parmesan_cheese = consumable("Parmesan cheese", "Parmesan cheese", ["hp",random.randint(1,8)], isFood = True)
Worcestershire_sauce = consumable("Worcestershire sauce", "Worcestershire sauce", ["hp",random.randint(1,8)], isFood = True)
black_eyed_peas = consumable("Black-eyed peas", "Black-eyed peas", ["hp",random.randint(1,8)], isFood = True)
cinnamon = consumable("Cinnamon", "Cinnamon", ["hp",random.randint(1,8)], isFood = True)
corn_flour = consumable("Corn flour", "Corn flour", ["hp",random.randint(1,8)], isFood = True)
barley = consumable("Barley", "Barley", ["hp",random.randint(1,8)], isFood = True)
summer_squash = consumable("Summer squash", "Summer squash", ["hp",random.randint(1,8)], isFood = True)
navy_beans = consumable("Navy beans", "Navy beans", ["hp",random.randint(1,8)], isFood = True)
amaretto = consumable("Amaretto", "Amaretto", ["hp",random.randint(1,8)], isFood = True)
rice = consumable("Rice", "Rice", ["hp",random.randint(1,8)], isFood = True)
chipotle_peppers = consumable("Chipotle peppers", "Chipotle peppers", ["hp",random.randint(1,8)], isFood = True)
dried_leeks = consumable("Dried leeks", "Dried leeks", ["hp",random.randint(1,8)], isFood = True)
huckleberries = consumable("Huckleberries", "Huckleberries", ["hp",random.randint(1,8)], isFood = True)
celery_seeds = consumable("Celery seeds", "Celery seeds", ["hp",random.randint(1,8)], isFood = True)
tomato_juice = consumable("Tomato juice", "Tomato juice", ["hp",random.randint(1,8)], isFood = True)
walnuts = consumable("Walnuts", "Walnuts", ["hp",random.randint(1,8)], isFood = True)
tomato_puree = consumable("Tomato puree", "Tomato puree", ["hp",random.randint(1,8)], isFood = True)
acorn_squash = consumable("Acorn squash", "Acorn squash", ["hp",random.randint(1,8)], isFood = True)
red_snapper = consumable("Red snapper", "Red snapper", ["hp",random.randint(1,8)], isFood = True)
portabella_mushrooms = consumable("Portabella mushrooms", "Portabella mushrooms", ["hp",random.randint(1,8)], isFood = True)
grapefruits = consumable("Grapefruits", "Grapefruits", ["hp",random.randint(1,8)], isFood = True)
pine_nuts = consumable("Pine nuts", "Pine nuts", ["hp",random.randint(1,8)], isFood = True)
chicken_liver = consumable("Chicken liver", "Chicken liver", ["hp",random.randint(1,8)], isFood = True)
almond_extract = consumable("Almond extract", "Almond extract", ["hp",random.randint(1,8)], isFood = True)
tarragon = consumable("Tarragon", "Tarragon", ["hp",random.randint(1,8)], isFood = True)
plum_tomatoes = consumable("Plum tomatoes", "Plum tomatoes", ["hp",random.randint(1,8)], isFood = True)
pork = consumable("Pork", "Pork", ["hp",random.randint(1,8)], isFood = True)
caviar = consumable("Caviar", "Caviar", ["hp",random.randint(1,8)], isFood = True)
heavy_cream = consumable("Heavy cream", "Heavy cream", ["hp",random.randint(1,8)], isFood = True)
mushrooms = consumable("Mushrooms", "Mushrooms", ["hp",random.randint(1,8)], isFood = True)
melons = consumable("Melons", "Melons", ["hp",random.randint(1,8)], isFood = True)
tofu = consumable("Tofu", "Tofu", ["hp",random.randint(1,8)], isFood = True)
lobsters = consumable("Lobsters", "Lobsters", ["hp",random.randint(1,8)], isFood = True)
aquavit = consumable("Aquavit", "Aquavit", ["hp",random.randint(1,8)], isFood = True)
sunflower_seeds = consumable("Sunflower seeds", "Sunflower seeds", ["hp",random.randint(1,8)], isFood = True)
coconuts = consumable("Coconuts", "Coconuts", ["hp",random.randint(1,8)], isFood = True)
prosciutto = consumable("Prosciutto", "Prosciutto", ["hp",random.randint(1,8)], isFood = True)
nectarines = consumable("Nectarines", "Nectarines", ["hp",random.randint(1,8)], isFood = True)
sushi = consumable("Sushi", "Sushi", ["hp",random.randint(1,8)], isFood = True)
mesclun_greens = consumable("Mesclun greens", "Mesclun greens", ["hp",random.randint(1,8)], isFood = True)
cream_cheese = consumable("Cream cheese", "Cream cheese", ["hp",random.randint(1,8)], isFood = True)
figs = consumable("Figs", "Figs", ["hp",random.randint(1,8)], isFood = True)
rice_vinegar = consumable("Rice vinegar", "Rice vinegar", ["hp",random.randint(1,8)], isFood = True)
baking_soda = consumable("Baking soda", "Baking soda", ["hp",random.randint(1,8)], isFood = True)
chard = consumable("Chard", "Chard", ["hp",random.randint(1,8)], isFood = True)
passion_fruit = consumable("Passion fruit", "Passion fruit", ["hp",random.randint(1,8)], isFood = True)
bass = consumable("Bass", "Bass", ["hp",random.randint(1,8)], isFood = True)
lettuce = consumable("Lettuce", "Lettuce", ["hp",random.randint(1,8)], isFood = True)
spaghetti_squash = consumable("Spaghetti squash", "Spaghetti squash", ["hp",random.randint(1,8)], isFood = True)
catfish = consumable("Catfish", "Catfish", ["hp",random.randint(1,8)], isFood = True)
peanuts = consumable("Peanuts", "Peanuts", ["hp",random.randint(1,8)], isFood = True)
mussels = consumable("Mussels", "Mussels", ["hp",random.randint(1,8)], isFood = True)
cream_of_tartar = consumable("Cream of tartar", "Cream of tartar", ["hp",random.randint(1,8)], isFood = True)
soybeans = consumable("Soybeans", "Soybeans", ["hp",random.randint(1,8)], isFood = True)
black_olives = consumable("Black olives", "Black olives", ["hp",random.randint(1,8)], isFood = True)
onions = consumable("Onions", "Onions", ["hp",random.randint(1,8)], isFood = True)
french_fries = consumable("French fries", "French fries", ["hp",random.randint(1,8)], isFood = True)
sauerkraut = consumable("Sauerkraut", "Sauerkraut", ["hp",random.randint(1,8)], isFood = True)
unsweetened_chocolate = consumable("Unsweetened chocolate", "Unsweetened chocolate", ["hp",random.randint(1,8)], isFood = True)
almond_butter = consumable("Almond butter", "Almond butter", ["hp",random.randint(1,8)], isFood = True)
bagels = consumable("Bagels", "Bagels", ["hp",random.randint(1,8)], isFood = True)
pecans = consumable("Pecans", "Pecans", ["hp",random.randint(1,8)], isFood = True)
brazil_nuts = consumable("Brazil nuts", "Brazil nuts", ["hp",random.randint(1,8)], isFood = True)
pink_beans = consumable("Pink beans", "Pink beans", ["hp",random.randint(1,8)], isFood = True)
tartar_sauce = consumable("Tartar sauce", "Tartar sauce", ["hp",random.randint(1,8)], isFood = True)
Romano_cheese = consumable("Romano cheese", "Romano cheese", ["hp",random.randint(1,8)], isFood = True)
oregano = consumable("Oregano", "Oregano", ["hp",random.randint(1,8)], isFood = True)
monkfish = consumable("Monkfish", "Monkfish", ["hp",random.randint(1,8)], isFood = True)
cod = consumable("Cod", "Cod", ["hp",random.randint(1,8)], isFood = True)
mustard = consumable("Mustard", "Mustard", ["hp",random.randint(1,8)], isFood = True)
turnips = consumable("Turnips", "Turnips", ["hp",random.randint(1,8)], isFood = True)
buckwheat = consumable("Buckwheat", "Buckwheat", ["hp",random.randint(1,8)], isFood = True)
beer = consumable("Beer", "Beer", ["hp",random.randint(1,8)], isFood = True)
ancho_chile_peppers = consumable("Ancho chile peppers", "Ancho chile peppers", ["hp",random.randint(1,8)], isFood = True)
graham_crackers = consumable("Graham crackers", "Graham crackers", ["hp",random.randint(1,8)], isFood = True)
succotash = consumable("Succotash", "Succotash", ["hp",random.randint(1,8)], isFood = True)
cookies = consumable("Cookies", "Cookies", ["hp",random.randint(1,8)], isFood = True)
berries = consumable("Berries", "Berries", ["hp",random.randint(1,8)], isFood = True)
English_muffins = consumable("English muffins", "English muffins", ["hp",random.randint(1,8)], isFood = True)
tortillas = consumable("Tortillas", "Tortillas", ["hp",random.randint(1,8)], isFood = True)
rose_water = consumable("Rose water", "Rose water", ["hp",random.randint(1,8)], isFood = True)
venison = consumable("Venison", "Venison", ["hp",random.randint(1,8)], isFood = True)
limes = consumable("Limes", "Limes", ["hp",random.randint(1,8)], isFood = True)
corned_beef = consumable("Corned beef", "Corned beef", ["hp",random.randint(1,8)], isFood = True)
sazon = consumable("Sazon", "Sazon", ["hp",random.randint(1,8)], isFood = True)
peanut_butter = consumable("Peanut butter", "Peanut butter", ["hp",random.randint(1,8)], isFood = True)
cantaloupes = consumable("Cantaloupes", "Cantaloupes", ["hp",random.randint(1,8)], isFood = True)
dates = consumable("Dates", "Dates", ["hp",random.randint(1,8)], isFood = True)
pumpkins = consumable("Pumpkins", "Pumpkins", ["hp",random.randint(1,8)], isFood = True)
asiago_cheese = consumable("Asiago cheese", "Asiago cheese", ["hp",random.randint(1,8)], isFood = True)
plantains = consumable("Plantains", "Plantains", ["hp",random.randint(1,8)], isFood = True)
lemon_Peel = consumable("Lemon peel", "Lemon peel", ["hp",random.randint(1,8)], isFood = True)
vanilla = consumable("Vanilla", "Vanilla", ["hp",random.randint(1,8)], isFood = True)
shallots = consumable("Shallots", "Shallots", ["hp",random.randint(1,8)], isFood = True)
cider_vinegar = consumable("Cider vinegar", "Cider vinegar", ["hp",random.randint(1,8)], isFood = True)
grouper = consumable("Grouper", "Grouper", ["hp",random.randint(1,8)], isFood = True)
soy_sauce = consumable("Soy sauce", "Soy sauce", ["hp",random.randint(1,8)], isFood = True)
tomatoes = consumable("Tomatoes", "Tomatoes", ["hp",random.randint(1,8)], isFood = True)
bok_choy = consumable("Bok choy", "Bok choy", ["hp",random.randint(1,8)], isFood = True)
chile_peppers = consumable("Chile peppers", "Chile peppers", ["hp",random.randint(1,8)], isFood = True)
squid = consumable("Squid", "Squid", ["hp",random.randint(1,8)], isFood = True)
ginger = consumable("Ginger", "Ginger", ["hp",random.randint(1,8)], isFood = True)
balsamic_vinegar = consumable("Balsamic vinegar", "Balsamic vinegar", ["hp",random.randint(1,8)], isFood = True)
squash = consumable("Squash", "Squash", ["hp",random.randint(1,8)], isFood = True)
macaroni = consumable("Macaroni", "Macaroni", ["hp",random.randint(1,8)], isFood = True)
gelatin = consumable("Gelatin", "Gelatin", ["hp",random.randint(1,8)], isFood = True)
shrimp = consumable("Shrimp", "Shrimp", ["hp",random.randint(1,8)], isFood = True)
bacon_grease = consumable("Bacon grease", "Bacon grease", ["hp",random.randint(1,8)], isFood = True)
apple_butter = consumable("Apple butter", "Apple butter", ["hp",random.randint(1,8)], isFood = True)
Mandarin_oranges = consumable("Mandarin oranges", "Mandarin oranges", ["hp",random.randint(1,8)], isFood = True)
buttermilk = consumable("Buttermilk", "Buttermilk", ["hp",random.randint(1,8)], isFood = True)
bean_sprouts = consumable("Bean sprouts", "Bean sprouts", ["hp",random.randint(1,8)], isFood = True)
potatoes = consumable("Potatoes", "Potatoes", ["hp",random.randint(1,8)], isFood = True)
date_sugar = consumable("Date sugar", "Date sugar", ["hp",random.randint(1,8)], isFood = True)
rice_paper = consumable("Rice paper", "Rice paper", ["hp",random.randint(1,8)], isFood = True)
butter = consumable("Butter", "Butter", ["hp",random.randint(1,8)], isFood = True)
chicken = consumable("Chicken", "Chicken", ["hp",random.randint(1,8)], isFood = True)
lima_beans = consumable("Lima beans", "Lima beans", ["hp",random.randint(1,8)], isFood = True)
half_and_half = consumable("Half-and-half", "Half-and-half", ["hp",random.randint(1,8)], isFood = True)
tomato_sauce = consumable("Tomato sauce", "Tomato sauce", ["hp",random.randint(1,8)], isFood = True)
red_chile_powder = consumable("Red chile powder", "Red chile powder", ["hp",random.randint(1,8)], isFood = True)
capers = consumable("Capers", "Capers", ["hp",random.randint(1,8)], isFood = True)
fennel = consumable("Fennel", "Fennel", ["hp",random.randint(1,8)], isFood = True)
liver = consumable("Liver", "Liver", ["hp",random.randint(1,8)], isFood = True)
sweet_potatoes = consumable("Sweet potatoes", "Sweet potatoes", ["hp",random.randint(1,8)], isFood = True)
alfredo_sauce = consumable("Alfredo sauce", "Alfredo sauce", ["hp",random.randint(1,8)], isFood = True)
hot_sauce = consumable("Hot sauce", "Hot sauce", ["hp",random.randint(1,8)], isFood = True)
bruschetta = consumable("Bruschetta", "Bruschetta", ["hp",random.randint(1,8)], isFood = True)
basil = consumable("Basil", "Basil", ["hp",random.randint(1,8)], isFood = True)
thyme = consumable("Thyme", "Thyme", ["hp",random.randint(1,8)], isFood = True)
romaine_lettuce = consumable("Romaine lettuce", "Romaine lettuce", ["hp",random.randint(1,8)], isFood = True)
crabs = consumable("Crabs", "Crabs", ["hp",random.randint(1,8)], isFood = True)
flax_seed = consumable("Flax seed", "Flax seed", ["hp",random.randint(1,8)], isFood = True)
honey = consumable("Honey", "Honey", ["hp",random.randint(1,8)], isFood = True)
green_onions = consumable("Green onions", "Green onions", ["hp",random.randint(1,8)], isFood = True)
duck = consumable("Duck", "Duck", ["hp",random.randint(1,8)], isFood = True)
pepper = consumable("Pepper", "Pepper", ["hp",random.randint(1,8)], isFood = True)
bourbon = consumable("Bourbon", "Bourbon", ["hp",random.randint(1,8)], isFood = True)
cocoa_powder = consumable("Cocoa powder", "Cocoa powder", ["hp",random.randint(1,8)], isFood = True)
pumpkin_seeds = consumable("Pumpkin seeds", "Pumpkin seeds", ["hp",random.randint(1,8)], isFood = True)
wasabi = consumable("Wasabi", "Wasabi", ["hp",random.randint(1,8)], isFood = True)
cremini_mushrooms = consumable("Cremini mushrooms", "Cremini mushrooms", ["hp",random.randint(1,8)], isFood = True)
curry_leaves = consumable("Curry leaves", "Curry leaves", ["hp",random.randint(1,8)], isFood = True)
red_cabbage = consumable("Red cabbage", "Red cabbage", ["hp",random.randint(1,8)], isFood = True)
trout = consumable("Trout", "Trout", ["hp",random.randint(1,8)], isFood = True)
cilantro = consumable("Cilantro", "Cilantro", ["hp",random.randint(1,8)], isFood = True)
cream = consumable("Cream", "Cream", ["hp",random.randint(1,8)], isFood = True)
chocolate = consumable("Chocolate", "Chocolate", ["hp",random.randint(1,8)], isFood = True)
hamburger = consumable("Hamburger", "Hamburger", ["hp",random.randint(1,8)], isFood = True)
beets = consumable("Beets", "Beets", ["hp",random.randint(1,8)], isFood = True)
tuna = consumable("Tuna", "Tuna", ["hp",random.randint(1,8)], isFood = True)
brown_rice = consumable("Brown rice", "Brown rice", ["hp",random.randint(1,8)], isFood = True)
cherries = consumable("Cherries", "Cherries", ["hp",random.randint(1,8)], isFood = True)
kidney_beans = consumable("Kidney beans", "Kidney beans", ["hp",random.randint(1,8)], isFood = True)
mascarpone = consumable("Mascarpone", "Mascarpone", ["hp",random.randint(1,8)], isFood = True)
baking_powder = consumable("Baking powder", "Baking powder", ["hp",random.randint(1,8)], isFood = True)
bacon = consumable("Bacon", "Bacon", ["hp",random.randint(1,8)], isFood = True)
grits = consumable("Grits", "Grits", ["hp",random.randint(1,8)], isFood = True)
jack_cheese = consumable("Jack cheese", "Jack cheese", ["hp",random.randint(1,8)], isFood = True)
red_beans = consumable("Red beans", "Red beans", ["hp",random.randint(1,8)], isFood = True)
pheasants = consumable("Pheasants", "Pheasants", ["hp",random.randint(1,8)], isFood = True)
beans = consumable("Beans", "Beans", ["hp",random.randint(1,8)], isFood = True)
cottage_cheese = consumable("Cottage cheese", "Cottage cheese", ["hp",random.randint(1,8)], isFood = True)
paprika = consumable("Paprika", "Paprika", ["hp",random.randint(1,8)], isFood = True)
avocados = consumable("Avocados", "Avocados", ["hp",random.randint(1,8)], isFood = True)
corn_syrup = consumable("Corn syrup", "Corn syrup", ["hp",random.randint(1,8)], isFood = True)
truffles = consumable("Truffles", "Truffles", ["hp",random.randint(1,8)], isFood = True)
applesauce = consumable("Applesauce", "Applesauce", ["hp",random.randint(1,8)], isFood = True)
ale = consumable("Ale", "Ale", ["hp",random.randint(1,8)], isFood = True)
breadfruit = consumable("Breadfruit", "Breadfruit", ["hp",random.randint(1,8)], isFood = True)
water = consumable("Water", "Water", ["hp",random.randint(1,8)], isFood = True)
turtle = consumable("Turtle", "Turtle", ["hp",random.randint(1,8)], isFood = True)
broccoli_raab = consumable("Broccoli raab", "Broccoli raab", ["hp",random.randint(1,8)], isFood = True)
watermelons = consumable("Watermelons", "Watermelons", ["hp",random.randint(1,8)], isFood = True)
dill = consumable("Dill", "Dill", ["hp",random.randint(1,8)], isFood = True)
wine = consumable("Wine", "Wine", ["hp",random.randint(1,8)], isFood = True)
loaf_of_bread = consumable("Loaf of bread", "Loaf of bread", ["hp",random.randint(1,8)], isFood = True)
plums = consumable("Plums", "Plums", ["hp",random.randint(1,8)], isFood = True)
corn = consumable("Corn", "Corn", ["hp",random.randint(1,8)], isFood = True)
raspberries = consumable("Raspberries", "Raspberries", ["hp",random.randint(1,8)], isFood = True)
snapper = consumable("Snapper", "Snapper", ["hp",random.randint(1,8)], isFood = True)
cashew_nut = consumable("Cashew nut", "Cashew nut", ["hp",random.randint(1,8)], isFood = True)
horseradish = consumable("Horseradish", "Horseradish", ["hp",random.randint(1,8)], isFood = True)
pinto_beans = consumable("Pinto beans", "Pinto beans", ["hp",random.randint(1,8)], isFood = True)
split_peas = consumable("Split peas", "Split peas", ["hp",random.randint(1,8)], isFood = True)
spearmint = consumable("Spearmint", "Spearmint", ["hp",random.randint(1,8)], isFood = True)


food_list =  [lamb, walnuts, raisins, artichokes, pears, parsnips, dumpling, olive_oil, swiss_cheese, bean_sprouts, beer, breadcrumbs, fennel_seeds, truffles, oranges, almonds, dried_leeks, vanilla_bean, oatmeal, apricots, dill, rum, crayfish, white_beans, tomato_sauce, feta_cheese, zinfandel_wine, duck, chicken_liver, broccoli_raab, steak, pancetta, arugula, kale, oatmeal, green_beans, pea_beans, rice_wine, cider, anchovy_paste, prawns, water_chestnuts, ham, lamb, gouda, octopus, provolone, sage, peas, adobo, blueberries, raw_sugar, herring, shitakes, bay_leaves, chai, cucumbers, sugar, snow_peas, apples, sausages, chili_sauce, Tabasco_sauce, beef, poppy_seeds, coffee, mayonnaise, broth, cayenne_pepper, raisins, salmon, barley_sugar, prunes, clams, asparagus, pears, wild_rice, cumin, tomato_paste, cooking_wine, brussels_sprouts, halibut, chives, oranges, hash_browns, lemon_grass, croutons, focaccia, geese, cranberries, cornstarch, jelly_beans, sesame_seeds, bouillon, chicory, couscous, condensed_milk, honeydew_melons, ketchup, mint, bean_threads, curry_powder, okra, carrots, sweet_peppers, brandy, eggplants, parsnips, apricots, sardines, Canadian_bacon, swiss_cheese, vinegar, almonds, bean_sauce, salt, blue_cheese, kumquats, orange_peels, crayfish, tea, pickles, snap_peas, colby_cheese, artificial_sweetener, red_pepper_flakes, aioli, zinfandel_wine, hazelnuts, gorgonzola, maple_syrup, cannellini_beans, alligator, habanero_chilies, sea_cucumbers, spinach, brown_sugar, olive_oil, vermouth, coconut_milk, veal, peaches, Irish_cream_liqueur, marmalade, borscht, coriander, milk, cabbage, mozzarella, dumpling, angelica, Cappuccino_Latte, ginger_ale, molasses, turkeys, cauliflower, ricotta_cheese, white_chocolate, rabbits, quail, apple_pie_spice, celery, pasta, Marsala, cactus, onion_powder, mustard_seeds, panko_bread_crumbs, canola_oil, chili_powder, papayas, scallops, lentils, lemon_juice, pineapples, cornmeal, pistachios, allspice, radishes, vegemite, chestnuts, five_spice_powder, flounder, Kahlua, granola, sour_cream, blackberries, black_beans, moo_shu_wrappers, pesto, white_beans, lemons, rosemary, cheddar_cheese, soymilk, chambord, wine_vinegar, mackerel, andouille_sausage, margarine, haddock, remoulade, kiwi, zest, potato_chips, garlic_powder, flour, steak, grapes, swordfish, creme_fraiche, fennel_seeds, olives, curry_paste, brunoise, strawberries, chutney, Goji_berry, broccoli, cloves, hoisin_sauce, guavas, rhubarb, artichokes, fish_sauce, custard, won_ton_skins, pomegranates, sherry, eggs, jicama, parsley, Parmesan_cheese, Worcestershire_sauce, black_eyed_peas, cinnamon, corn_flour, barley, summer_squash, navy_beans, amaretto, rice, chipotle_peppers, dried_leeks, huckleberries, celery_seeds, tomato_juice, walnuts, tomato_puree, acorn_squash, red_snapper, portabella_mushrooms, grapefruits, pine_nuts, chicken_liver, almond_extract, tarragon, plum_tomatoes, pork, caviar, heavy_cream, mushrooms, melons, tofu, lobsters, aquavit, sunflower_seeds, coconuts, prosciutto, nectarines, sushi, mesclun_greens, cream_cheese, figs, rice_vinegar, baking_soda, chard, passion_fruit, bass, lettuce, spaghetti_squash, catfish, peanuts, mussels, cream_of_tartar, soybeans, black_olives, onions, french_fries, sauerkraut, unsweetened_chocolate, almond_butter, bagels, pecans, brazil_nuts, pink_beans, tartar_sauce, Romano_cheese, oregano, monkfish, cod, mustard, turnips, buckwheat, beer, ancho_chile_peppers, graham_crackers, succotash, cookies, berries, English_muffins, tortillas, rose_water, venison, limes, corned_beef, sazon, peanut_butter, cantaloupes, dates, pumpkins, asiago_cheese, plantains, lemon_Peel, vanilla, shallots, cider_vinegar, grouper, soy_sauce, tomatoes, bok_choy, chile_peppers, squid, ginger, balsamic_vinegar, squash, macaroni, gelatin, shrimp, bacon_grease, apple_butter, Mandarin_oranges, buttermilk, bean_sprouts, potatoes, date_sugar, rice_paper, butter, chicken, lima_beans, half_and_half, tomato_sauce, red_chile_powder, capers, fennel, liver, sweet_potatoes, alfredo_sauce, hot_sauce, bruschetta, basil, thyme, romaine_lettuce, crabs, flax_seed, honey, green_onions, duck, pepper, bourbon, cocoa_powder, pumpkin_seeds, wasabi, cremini_mushrooms, curry_leaves, red_cabbage, trout, cilantro, cream, chocolate, hamburger, beets, tuna, brown_rice, cherries, kidney_beans, mascarpone, baking_powder, bacon, grits, jack_cheese, red_beans, pheasants, beans, cottage_cheese, paprika, avocados, corn_syrup, truffles, applesauce, ale, breadfruit, water, turtle, broccoli_raab, watermelons, dill, wine, loaf_of_bread, plums, corn, raspberries, snapper, cashew_nut, horseradish, pinto_beans, split_peas, spearmint, vanilla_bean, cherries, garlic, anchovies, almond_paste, breadcrumbs, bananas]
