from weapon import weapon

#WEAPONS
oldSpear = weapon("Old Spear", 0, 1, "stab", "It's seen better days")
oldSword = weapon("Old Sword", 1, 0, "slash", "It's seen better days")
oldHammer = weapon("Old Hammer", 2, -1, "swing", "It's seen better days")

magic_wand = weapon("Wand", 0, 0, "wave", "A simple wand.")
shortsword = weapon("Shortsword", 1 , 1 , "slash", "A simple shortsword")
makeshift_bow = weapon("Makeshift bow", 1, 1, "shoot", "A simple makeshift bow.")
makeshift_spear = weapon("Makeshift spear", 1,1, "stab", "A simple spear")

Battle_axe = weapon("Battle axe", 1, 1, "Weapon", "A Battle axe")
bludgeon = weapon("Bludgeon", 1, 1, "Weapon", "A Bludgeon")
club = weapon("Club", 1, 1, "Weapon", "A Club")
flail = weapon("Flail", 1, 1, "Weapon", "A Flail")
flanged_mace = weapon("Flanged mace", 1, 1, "Weapon", "A Flanged mace")
pick = weapon("Pick", 1, 1, "Weapon", "A Pick")
mace = weapon("Mace", 1, 1, "Weapon", "A Mace")
morning_star = weapon("Morning star", 1, 1, "Weapon", "A Morning star")
quarterstaff = weapon("Quarterstaff", 1, 1, "Weapon", "A Quarterstaff")
war_hammer = weapon("War hammer", 1, 1, "Weapon", "A War hammer")
arming_sword = weapon("Arming sword", 1, 1, "Weapon", "A Arming sword")
dagger = weapon("Dagger", 1, 1, "Weapon", "A Dagger")
war_scythe = weapon("War scythe", 1, 1, "Weapon", "A War scythe")
bow = weapon("Bow", 1, 1, "Weapon", "A Bow")
longbow = weapon("Longbow", 1, 1, "Weapon", "A Longbow")
recurve_bow = weapon("Recurve bow", 1, 1, "Weapon", "A Recurve bow")
crossbow = weapon("Crossbow", 1, 1, "Weapon", "A Crossbow")
arbalest = weapon("Arbalest", 1, 1, "Weapon", "A Arbalest")
repeating_crossbow = weapon("Repeating crossbow", 1, 1, "Weapon", "A Repeating crossbow")
sling = weapon("Sling", 1, 1, "Weapon", "A Sling")
throwing_knife = weapon("Throwing knife", 1, 1, "Weapon", "A Throwing knife")
throwing_spear = weapon("Throwing spear", 1, 1, "Weapon", "A Throwing spear")
javelin = weapon("Javelin", 1, 1, "Weapon", "A Javelin")
club = weapon("Club", 1, 1, "Weapon", "A Club")
dagger = weapon("Dagger", 1, 1, "Weapon", "A Dagger")
greatclub = weapon("Greatclub", 1, 1, "Weapon", "A Greatclub")
handaxe = weapon("Handaxe", 1, 1, "Weapon", "A Handaxe")
javelin = weapon("Javelin", 1, 1, "Weapon", "A Javelin")
mace = weapon("Mace", 1, 1, "Weapon", "A Mace")
sickle = weapon("Sickle", 1, 1, "Weapon", "A Sickle")
dart = weapon("Dart", 1, 1, "Weapon", "A Dart")
scimitar = weapon("Scimitar", 1, 1, "Weapon", "A Scimitar")
rapier = weapon("Rapier", 1, 1, "Weapon", "A Rapier")
trident = weapon("Trident", 1, 1, "Weapon", "A Trident")
whip = weapon("Whip", 1, 1, "Weapon", "A Whip")
maul = weapon("Maul", 1, 1, "Weapon", "A Maul")
lance = weapon("Lance", 1, 1, "Weapon", "A Lance")

weapon_list = ['Battle axe', 'bludgeon', 'club', 'flail', 'flanged mace', 'pick', 'mace', 'morning star', 'quarterstaff', 'war hammer', 'arming sword', 'dagger', 'estoc', 'falchion', 'katana', 'knife', 'longsword', 'rapier', 'sabre', 'shortsword', 'glaive', 'lance', 'halberd', 'axe', 'pike', 'war scythe', 'bow', 'longbow', 'recurve bow', 'crossbow', 'arbalest', 'repeating crossbow', 'sling', 'throwing knife', 'throwing spear', 'javelin', 'club', 'dagger', 'greatclub', 'handaxe', 'javelin', 'mace', 'sickle', 'dart', 'scimitar', 'rapier', 'trident', 'whip', 'maul', 'lance']
